language: java

jdk:
- oraclejdk8

before_install:
- cd PolicyLanguage
- sudo curl -O http://www.antlr.org/download/antlr-4.4-complete.jar
- java -jar antlr-4.4-complete.jar PoL.g4
- cd ..
- sudo cp -n -a PolicyLanguage/target/generated-sources/antlr4/* PolicyLanguageCore/src/structure/
- cd /PolicyLanguageCore

script: mvn test