language: java

jdk:
- oraclejdk8

before_install:
- cd /usr/local/lib
- sudo wget http://www.antlr.org/download/antlr-4.4-complete.jar
- export CLASSPATH=".:/usr/local/lib/antlr-4.4-complete.jar:$CLASSPATH"
- alias antlr4='java -jar /usr/local/lib/antlr-4.5.3-complete.jar'
- alias grun='java org.antlr.v4.gui.TestRig'
- cd $TRAVIS_BUILD_DIR
- cd PolicyLanguage
- antlr4 PoL.g4
- cd ..
- cp -n -a /PolicyLanguage/target/generated-sources/antlr4/. /PolicyLanguageCore/src/structure/
- cd /PolicyLanguageCore

script: mvn test